"""Static visuals, generated by matplotlib into `reports/`.

Two rules from the design direction, and they are the reason these exist at all:

* **Confidence bands get equal visual weight to the lines.** The argument of the
  whole project is that a bare rate is not a result, so a chart that draws the
  point estimate boldly and the uncertainty faintly would contradict its own
  content.
* **Shape as well as colour.** These end up as screenshots in a README and have
  to survive greyscale, so every series carries a distinct marker and the
  coverage grid hatches its states.

Numbers are set in a monospace face and prose in a sans face, the way a lab
notebook separates a measurement from a caption.
"""

from __future__ import annotations

import textwrap
from collections.abc import Mapping, Sequence
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.patches import Rectangle

from crucible.archive.grid import all_cell_keys
from crucible.loop.reports import RoundReport
from crucible.loop.statistics import Proportion
from crucible.schemas.agreement import UNMEASURED_CAPTION, ClassifierAgreement
from crucible.schemas.taxonomy import GRID_DENOMINATOR

MONO = ["DejaVu Sans Mono", "monospace"]
SANS = ["DejaVu Sans", "sans-serif"]

#: Quiet ink for everything that is not the coverage grid.
INK = "#1c1c1c"
MUTED = "#8a8a8a"
#: For a caption that says a number should not be trusted.
SOFT = "#a8541f"
SERIES = {
    "archive": ("#2f6f9f", "o", "-", "//"),
    "holdout": ("#b4552d", "s", "--", "\\\\"),
    "utility": ("#4a7c59", "^", ":", ".."),
}
GRID_COLOURS = ("#f5f3ef", "#cfe0ec", "#8fb8d4", "#4f8db8", "#2f6f9f")


def _style() -> None:
    plt.rcParams.update(
        {
            "font.family": SANS,
            "axes.titlesize": 12,
            "axes.labelsize": 10,
            "axes.edgecolor": MUTED,
            "axes.labelcolor": INK,
            "text.color": INK,
            "xtick.color": INK,
            "ytick.color": INK,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "axes.grid": True,
            "grid.color": "#e6e4e0",
            "grid.linewidth": 0.6,
            "legend.frameon": False,
        }
    )


def three_curves(rounds: Sequence[RoundReport], path: Path) -> Path:
    """Archive, holdout and utility rates across rounds, with their bands.

    The gap between the first two lines is the story: it is the overfitting
    measure, and it is drawn as the space between two bands rather than quoted
    as a number the reader has to trust.
    """
    _style()
    figure, axes = plt.subplots(figsize=(8.5, 4.6), constrained_layout=True)

    if not rounds:
        axes.text(
            0.5,
            0.5,
            "No rounds yet.\nStart a run with `crucible loop start --rounds 8`",
            ha="center",
            va="center",
            fontfamily=MONO,
            color=MUTED,
        )
        axes.set_axis_off()
        return _save(figure, path)

    numbers = [report.round_number for report in rounds]
    series = {
        "archive": [report.archive_block for report in rounds],
        "holdout": [report.holdout_block for report in rounds],
        "utility": [report.utility_pass for report in rounds],
    }
    labels = {
        "archive": "archive block rate",
        "holdout": "holdout block rate",
        "utility": "utility pass rate",
    }

    for key, proportions in series.items():
        colour, marker, dash, hatch = SERIES[key]
        rates = [item.rate for item in proportions]
        lows = [item.interval[0] for item in proportions]
        highs = [item.interval[1] for item in proportions]
        # The band is as heavy as the line: uncertainty is part of the result.
        # Bands overlap, so each is hatched as well as tinted; the hatch is what
        # tells them apart once three of them stack.
        axes.fill_between(
            numbers,
            lows,
            highs,
            facecolor=colour,
            edgecolor=colour,
            alpha=0.18,
            linewidth=0,
            hatch=hatch,
        )
        axes.plot(
            numbers,
            lows,
            color=colour,
            linewidth=0.8,
            linestyle=dash,
            alpha=0.55,
        )
        axes.plot(numbers, highs, color=colour, linewidth=0.8, linestyle=dash, alpha=0.55)
        axes.plot(
            numbers,
            rates,
            color=colour,
            marker=marker,
            markersize=6,
            linewidth=1.8,
            linestyle=dash,
            label=f"{labels[key]}  {_sample_size(proportions)}",
        )

    axes.set_xlabel("round")
    axes.set_ylabel("rate")
    axes.set_ylim(-0.02, 1.02)
    axes.set_xticks(numbers)
    for label in [*axes.get_xticklabels(), *axes.get_yticklabels()]:
        label.set_fontfamily(MONO)
    axes.set_title(
        "Block rates and utility across rounds, with 95% Wilson intervals",
        loc="left",
    )
    axes.legend(loc="lower right", prop={"family": SANS, "size": 9})
    return _save(figure, path)


def _sample_size(proportions: Sequence[Proportion]) -> str:
    """The denominator, so a reader can see why a band is as wide as it is.

    A holdout band that swamps the plot is not noise in the chart, it is the
    consequence of n=3, and the legend has to say so.
    """
    counts = {item.trials for item in proportions}
    if len(counts) == 1:
        return f"(n={counts.pop()})"
    return f"(n={min(counts)}-{max(counts)})"


def coverage_grid(
    fitness_by_cell: Mapping[str, float],
    occupancy_by_cell: Mapping[str, int],
    path: Path,
    *,
    title: str = "Coverage",
    agreement: ClassifierAgreement | None = None,
) -> Path:
    """The 96-cell grid: the signature visual.

    Rows are objective x vector, columns are technique. Colour is elite fitness;
    hatching marks a cell that is occupied but has no scored elite yet, so the
    two states stay distinguishable in greyscale.
    """
    _style()
    keys = all_cell_keys()
    objectives = sorted({key.split("|")[0] for key in keys})
    vectors = sorted({key.split("|")[1] for key in keys})
    techniques = sorted({key.split("|")[2] for key in keys})
    rows = [(objective, vector) for objective in objectives for vector in vectors]

    figure, axes = plt.subplots(figsize=(11.5, 7.2), constrained_layout=True)
    highest = max(fitness_by_cell.values(), default=0.0) or 1.0

    for row_index, (objective, vector) in enumerate(rows):
        for column, technique in enumerate(techniques):
            key = f"{objective}|{vector}|{technique}"
            occupancy = occupancy_by_cell.get(key, 0)
            fitness = fitness_by_cell.get(key)
            colour = GRID_COLOURS[0]
            hatch = None
            if occupancy:
                if fitness is None:
                    hatch = "//"
                    colour = GRID_COLOURS[1]
                else:
                    step = min(
                        len(GRID_COLOURS) - 1,
                        1 + int((fitness / highest) * (len(GRID_COLOURS) - 2)),
                    )
                    colour = GRID_COLOURS[step]
            axes.add_patch(
                Rectangle(
                    (column, row_index),
                    1,
                    1,
                    facecolor=colour,
                    edgecolor="white",
                    linewidth=1.5,
                    hatch=hatch,
                )
            )
            if occupancy:
                axes.text(
                    column + 0.5,
                    row_index + 0.5,
                    str(occupancy),
                    ha="center",
                    va="center",
                    fontfamily=MONO,
                    fontsize=9,
                    color=INK if fitness is None else "white",
                )

    occupied = sum(1 for key in keys if occupancy_by_cell.get(key, 0))
    axes.set_xlim(0, len(techniques))
    axes.set_ylim(0, len(rows))
    axes.invert_yaxis()
    axes.set_xticks([index + 0.5 for index in range(len(techniques))])
    axes.set_xticklabels(techniques, rotation=35, ha="right", fontfamily=MONO, fontsize=8)
    axes.set_yticks([index + 0.5 for index in range(len(rows))])
    axes.set_yticklabels(
        [f"{objective} | {vector}" for objective, vector in rows],
        fontfamily=MONO,
        fontsize=8,
    )
    axes.set_title(
        f"{title} — {occupied}/{GRID_DENOMINATOR} cells occupied "
        f"({occupied / GRID_DENOMINATOR:.0%})",
        loc="left",
    )
    axes.grid(False)
    axes.text(
        0,
        -0.9,
        "cell colour: elite fitness   hatched: occupied, no scored elite   number: attacks in cell",
        fontsize=8,
        color=MUTED,
    )
    # The grid's columns ARE the technique axis, so a reader looking at it is
    # exactly the reader who needs to know how much that axis can be trusted.
    caption = agreement.caption() if agreement is not None else UNMEASURED_CAPTION
    # Below the rotated technique labels, because the caption is about those
    # columns. `supxlabel` participates in the constrained layout, so a two-line
    # caption makes room for itself instead of running off the figure.
    figure.supxlabel(
        _wrap(caption),
        fontsize=8,
        color=SOFT if agreement is None or agreement.technique_is_soft else MUTED,
        fontfamily=MONO,
        ha="left",
        x=0.01,
    )
    return _save(figure, path)


#: Caption width in characters, so a long agreement line wraps rather than
#: running off the figure.
CAPTION_WIDTH = 110


def _wrap(text: str) -> str:
    return "\n".join(textwrap.wrap(text, CAPTION_WIDTH)) or text


def coverage_strip(per_round: Sequence[tuple[int, Mapping[str, int]]], path: Path) -> Path:
    """Small multiples: one miniature grid per round, so evolution is visible."""
    _style()
    if not per_round:
        figure, axes = plt.subplots(figsize=(6, 2), constrained_layout=True)
        axes.text(
            0.5,
            0.5,
            "No rounds yet.",
            ha="center",
            va="center",
            fontfamily=MONO,
            color=MUTED,
        )
        axes.set_axis_off()
        return _save(figure, path)

    keys = all_cell_keys()
    columns = len(per_round)
    figure, axes_row = plt.subplots(
        1, columns, figsize=(2.2 * columns, 3.0), constrained_layout=True, squeeze=False
    )
    for index, (round_number, occupancy) in enumerate(per_round):
        axes = axes_row[0][index]
        occupied = 0
        for position, key in enumerate(keys):
            row, column = divmod(position, 8)
            filled = occupancy.get(key, 0) > 0
            occupied += int(filled)
            axes.add_patch(
                Rectangle(
                    (column, row),
                    1,
                    1,
                    facecolor=GRID_COLOURS[3] if filled else GRID_COLOURS[0],
                    edgecolor="white",
                    linewidth=0.6,
                )
            )
        axes.set_xlim(0, 8)
        axes.set_ylim(0, len(keys) // 8)
        axes.invert_yaxis()
        axes.set_xticks([])
        axes.set_yticks([])
        axes.grid(False)
        axes.set_title(
            f"round {round_number}\n{occupied}/{GRID_DENOMINATOR}",
            fontsize=9,
            fontfamily=MONO,
        )
    figure.suptitle("Coverage evolution", ha="left", x=0.01, fontfamily=SANS[0])
    return _save(figure, path)


def _save(figure: Figure, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=140)
    plt.close(figure)
    return path
