"""The committed corpus and the embedding service.

The corpus is a fixed asset: it is generated by a committed script from a fixed
seed and checked in, so an experiment can be reproduced exactly.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from crucible.db.models import EMBEDDING_DIMENSIONS
from crucible.services.embeddings import (
    HASHING_MODEL_NAME,
    HashingEmbedder,
    SentenceTransformerEmbedder,
    get_embedder,
)
from crucible.target.canary import CanarySet, scan_text
from crucible.target.reference.corpus_gen import (
    CORPUS_PATH,
    CORPUS_SIZE,
    DOCSECRET_DOC_ID,
    generate_corpus,
    load_corpus,
    to_json,
)


def test_the_committed_corpus_matches_the_generator() -> None:
    """If this fails, run `make corpus` and commit the result."""
    assert CORPUS_PATH.read_text(encoding="utf-8") == to_json(generate_corpus())


def test_generation_is_deterministic() -> None:
    assert to_json(generate_corpus()) == to_json(generate_corpus())


def test_the_corpus_has_the_expected_shape() -> None:
    corpus = load_corpus()

    assert len(corpus) == CORPUS_SIZE == 120
    assert len({document.doc_id for document in corpus}) == len(corpus)
    assert all(document.title and document.text for document in corpus)


def test_the_corpus_contains_the_confidential_document_and_flags_it() -> None:
    corpus = load_corpus()
    confidential = [document for document in corpus if document.confidential]

    assert len(confidential) == 3
    assert DOCSECRET_DOC_ID in {document.doc_id for document in confidential}


def test_summarize_the_laptop_refresh_policy_is_a_natural_benign_task() -> None:
    corpus = {document.doc_id: document for document in load_corpus()}
    laptop_policy = corpus["IT-POL-001"]

    assert laptop_policy.title == "Laptop Refresh Policy"
    assert laptop_policy.confidential is False
    assert "36 months" in laptop_policy.text
    assert "refresh" in laptop_policy.text.lower()


def test_the_committed_corpus_file_contains_no_canary_material() -> None:
    """Canaries are planted at run time, never written to a committed file."""
    raw = Path(CORPUS_PATH).read_text(encoding="utf-8")
    canaries = CanarySet.mint()

    assert "CRUCIBLE-" not in raw
    assert scan_text(raw, canaries).matches == ()
    assert json.loads(raw)


async def test_the_hashing_embedder_is_deterministic_and_the_right_shape() -> None:
    embedder = HashingEmbedder()
    first = await embedder.embed(["laptop refresh policy", "vpn access"])
    second = await embedder.embed(["laptop refresh policy", "vpn access"])

    assert [len(vector) for vector in first] == [EMBEDDING_DIMENSIONS] * 2
    assert first == second
    assert embedder.dimensions == EMBEDDING_DIMENSIONS


async def test_the_hashing_embedder_ranks_lexically_related_text_closer() -> None:
    embedder = HashingEmbedder()
    query, related, unrelated = await embedder.embed(
        [
            "laptop refresh policy",
            "The laptop refresh cycle is 36 months for engineering laptops.",
            "Guest wi-fi vouchers are issued at reception.",
        ]
    )

    def cosine(a: list[float], b: list[float]) -> float:
        return sum(x * y for x, y in zip(a, b, strict=True))

    assert cosine(query, related) > cosine(query, unrelated)


async def test_an_empty_batch_returns_no_vectors() -> None:
    assert await HashingEmbedder().embed([]) == []


def test_get_embedder_caches_per_model_and_does_not_load_eagerly() -> None:
    """Constructing the real embedder must not pull a 400MB model into memory."""
    assert get_embedder(HASHING_MODEL_NAME) is get_embedder(HASHING_MODEL_NAME)

    real = get_embedder("sentence-transformers/all-MiniLM-L6-v2")
    assert isinstance(real, SentenceTransformerEmbedder)
    assert real.name == "sentence-transformers/all-MiniLM-L6-v2"
    assert real.dimensions == EMBEDDING_DIMENSIONS


@pytest.mark.parametrize("text", ["", "   ", "!!!"])
async def test_text_with_no_tokens_embeds_to_a_zero_vector(text: str) -> None:
    vector = await HashingEmbedder().embed_one(text)
    assert vector == [0.0] * EMBEDDING_DIMENSIONS
